services:
  inventory-api:
    build: ./apps/inventory-api
    image: inventory-api:0.1.0
    container_name: inventory-api
    environment:
      OTEL_SERVICE_NAME: inventory-api
      SERVICE_VERSION: 0.1.0
      DEPLOYMENT_ENVIRONMENT: local
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector
    restart: unless-stopped

  orders-api:
    build:
      context: ./apps/orders-api/OrdersApi
    image: orders-api:0.1.0
    container_name: orders-api
    environment:
      OTEL_SERVICE_NAME: orders-api
      SERVICE_VERSION: 0.1.0
      DEPLOYMENT_ENVIRONMENT: local
      INVENTORY_API_URL: http://inventory-api:8081
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
    depends_on:
      - inventory-api
      - otel-collector
    ports:
      - "8080:8080"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "14250:14250"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger
    restart: unless-stopped
