apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
      - name: web
        image: nginx
        env:
        - name: COLLECTOR_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: orders-api-configmap
              key: COLLECTOR_ENDPOINT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-api-secret
              key: DB_PASSWORD